[workspace]
resolver = "3"
members = [
  "common",
  "common/directive_derive",
  "keyboard",
  "syntoniq",
]

[workspace.package]
edition = "2024"
version  = "0.1.1"

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.57"
midir = "0.10.2"
midly = "0.5.3"
log = "0.4.28"
env_logger = "0.11.8"
toml = "0.9.5"
serde = { version = "1.0.219", features = ["derive", "rc"] }
anyhow = "1.0.99"
num-rational = { version = "0.4.2", features = ["serde"] }
askama = "0.14.0"
chrono = "0.4.42"
winnow = "0.7.13"
anstream = "0.6.20"
serde_json = "1.0.145"
annotate-snippets = "0.12.4"
primal = "0.3.3"
num-traits = "0.2.19"
num-integer = "0.1.46"
