[package]
name = "qlaunchpad"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
clap_complete = "4.5.55"
midir = "0.10.1"
midly = "0.5.3"
log = "0.4.27"
flume = "0.11.1"
env_logger = "0.11.8"
tokio = { version = "1.46.1", features = ["full"] }
