[package]
name = "qlaunchpad"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.41"
clap_complete = "4.5.55"
ctrlc = "3.4.7"
midir = "0.10.1"
midly = "0.5.3"
log = "0.4.27"
flume = "0.11.1"
env_logger = "0.11.8"
