[workspace]
resolver = "3"
members = [
  "common",
  "keyboard",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.41", features = ["derive"] }
clap_complete = "4.5.55"
midir = "0.10.1"
midly = "0.5.3"
log = "0.4.27"
env_logger = "0.11.8"
toml = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
num-rational = "0.4.2"
askama = "0.14.0"
chrono = "0.4.41"
winnow = "0.7.12"
