[workspace]
resolver = "3"
members = [
  "common",
  "common/directive_derive",
  "keyboard",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.57"
midir = "0.10.2"
midly = "0.5.3"
log = "0.4.28"
env_logger = "0.11.8"
toml = "0.9.5"
serde = { version = "1.0.219", features = ["derive", "rc"] }
anyhow = "1.0.99"
num-rational = { version = "0.4.2", features = ["serde"] }
askama = "0.14.0"
chrono = "0.4.42"
winnow = "0.7.13"
