[[scale]]
name = "EDO-31"
type = "EqualDivison"
# reference_freq is the pitch of the base of the scale and assigned MIDI note 60
# in adjusted MIDI mode. It would would typically be middle C for something used
# as a diatonic scale.
divisions = [31, 2, 1] # 31 divisions of the octave: [a, b, c] = ((b^c)^*(1/a))
reference_freq = "220*3\\12" # middle C for A-440 12-TET scale
note_names = [
  "C",
  "C↑", "C♯", "D♭", "D↓", "D",
  "D↑", "D♯", "E♭", "E↓", "E",
  "E↑", "F↓", "F",
  "F↑", "F♯", "G♭", "G↓", "G",
  "G↑", "G♯", "A♭", "A↓", "A",
  "A↑", "A♯", "B♭", "B↓", "B",
  "B↑", "C↓",
]

[[layout]]
name = "EDO-31-5x3"
ll = [1, 1]
ur = [8, 8]
base = [2, 2]
scale_name = "EDO-31"
steps = [5, 3]
