[[scale]]
name = "12-EDO"
type = "EqualDivision"
divisions = [12, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C♯", "D", "E♭", "E", "F", "F♯", "G", "G♯", "A", "B♭", "B"]

[[layout]]
name = "12-EDO-2x1"
base = {row = 3, col = 2}
scale_name = "12-EDO"
steps = {h = 2, v = 1}

[[layout]]
name = "12-EDO-2x5"
base = {row = 3, col = 2}
scale_name = "12-EDO"
steps = {h = 2, v = 5}

[[scale]]
name = "19-EDO"
type = "EqualDivision"
divisions = [19, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C♯", "D♭", "D", "D♯", "E♭", "E", "E♯", "F", "F♯", "G♭",
              "G", "G♯", "A♭", "A", "A♯", "B♭", "B", "B♯"]

[[layout]]
name = "19-EDO-2x1"
base = {row = 3, col = 2}
scale_name = "19-EDO"
steps = {h = 3, v = 2}

[[scale]]
name = "31-EDO"
type = "EqualDivision"
# reference_freq is the pitch of the base of the scale and assigned MIDI note 60
# in adjusted MIDI mode. It would would typically be middle C for something used
# as a diatonic scale.
divisions = [31, 2, 1]   # 31 divisions of the octave: [a, b, c] = ((b^c)^*(1/a))
base_pitch = "220*^3|12" # middle C for A-440 12-TET scale
note_names = [
  "C",
  "C↑", "C♯", "D♭", "D↓", "D",
  "D↑", "D♯", "E♭", "E↓", "E",
  "E↑", "F↓", "F",
  "F↑", "F♯", "G♭", "G↓", "G",
  "G↑", "G♯", "A♭", "A↓", "A",
  "A↑", "A♯", "B♭", "B↓", "B",
  "B↑", "C↓",
]

[[layout]]
name = "31-EDO-5x3"
base = {row = 2, col = 2}
scale_name = "31-EDO"
steps = {h = 5, v = 3}

[[layout]]
name = "31-EDO-9x5"
base = {row = 4, col = 2}
scale_name = "31-EDO"
steps = {h = 5, v = 9}

[[scale]]
name = "17-EDO"
type = "EqualDivision"
divisions = [17, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C#-", "C#+", "D+", "E%-", "E-", "E+", "F", "F#-",
              "F#+", "G", "A%-", "A%+", "A+", "B%-", "B-", "B+", "C"]

[[layout]]
name = "17-EDO-3x2"
base = {row = 3, col = 2}
scale_name = "17-EDO"
steps = {h = 3, v = 2}

[[layout]]
name = "17-EDO-2x7"
base = {row = 3, col = 5}
scale_name = "17-EDO"
steps = {h = 2, v = 7}

[[scale]]
name = "JI-11"
type = "Generic"
base_pitch = "220*^3|12"
pitches = [
  "[61]*2", "[62]*2", "[63]*2", "[64]*2", "[65]*2", "[66]*2", "[67]*2", "[68]*2",
  "[51]*2", "[52]*2", "[53]*2", "[54]*2", "[55]*2", "[56]*2", "[57]*2", "[58]*2",
  "17/16",  "16/15",   "6/5",   "11/8",   "17/12",  "8/5",     "7/4",   "16/9",
   "1",      "9/8",    "5/4",    "4/3",    "3/2",   "5/3",    "15/8",    "2",
  "[61]*1/2", "[62]*1/2", "[63]*1/2", "[64]*1/2", "[65]*1/2", "[66]*1/2", "[67]*1/2", "[68]*1/2",
  "[51]*1/2", "[52]*1/2", "[53]*1/2", "[54]*1/2", "[55]*1/2", "[56]*1/2", "[57]*1/2", "[58]*1/2",
  "[41]*1/2", "[42]*1/2", "[43]*1/2", "[44]*1/2", "[45]*1/2", "[46]*1/2", "[47]*1/2", "[48]*1/2",
  "[31]*1/2", "[32]*1/2", "[33]*1/2", "[34]*1/2", "[35]*1/2", "[36]*1/2", "[37]*1/2", "[38]*1/2",
]
note_names = [
 "C♯'", "D♭'", "E♭'", "H11'", "F♯'", "A♭'", "H7'", "B♭'",
 "C'",  "D'",  "E'",  "F'",   "G'",  "A'",  "B'",  "C'",
 "C♯", "D♭", "E♭", "H11", "F♯", "A♭", "H7", "B♭",
 "C",  "D",  "E",  "F",   "G",  "A",  "B",  "C",
 "C♯,", "D♭,", "E♭,", "H11,", "F♯,", "A♭,", "H7,", "B♭,",
 "C,",  "D,",  "E,",  "F,",   "G,",  "A,",  "B,",  "C,",
 "C♯,,", "D♭,,", "E♭,,", "H11,,", "F♯,,", "A♭,,", "H7,,", "B♭,,",
 "C,,",  "D,,",  "E,,",  "F,,",   "G,,",  "A,,",  "B,,",  "C,,",
]

[[layout]]
name = "Just Intonation (11)"
scale_name = "JI-11"

[[scale]]
# From Fabio Costa's Etude on Minor Thirds: https://www.youtube.com/watch?v=U7l7s1Vr6lQ
# See also minor-thirds.toml
name = "Minor Thirds 1"
type = "Generic"
base_pitch = "990.8"
# In spite of frequencies listed in the video, the lower note of the
# third always appears to have the same frequency.
pitches = [
  "15/13", "37/32", "22/19", "29/25", "36/31", "50/43", "7/6", "55/47",
   "1",     "1",     "1",     "1",     "1",     "1"   , "1",    "1",
  "11/13", "27/32", "16/19", "21/25", "26/31", "36/43", "5/6", "39/47",
  "9/13",  "22/32", "13/19", "17/25", "21/31", "29/43", "4/6", "31/47",
  "7/13",  "17/32", "10/19", "13/25", "16/31", "22/43", "3/6", "23/47",
  "5/13",  "12/32",  "7/19",  "9/25", "11/31", "15/43", "2/6", "15/47",
  "3/13" ,  "7/32",  "4/19",  "5/25",  "6/31", "08/43", "1/6",  "7/47",
  "1/13" ,  "2/32",  "1/19",  "1/25",  "1/31", "01/43",  "",     "",
]
note_names = [
   "15", "37", "22", "29", "36", "50", "7", "55",
   "13", "32", "19", "25", "31", "43", "6", "47",
   "11", "27", "16", "21", "26", "36", "5", "39",
    "9", "22", "13", "17", "21", "29", "4", "31",
    "7", "17", "10", "13", "16", "22", "3", "23",
    "5", "12",  "7",  "9", "11", "15", "2", "15",
    "3",  "7",  "4",  "5",  "6",  "8", "1",  "7",
    "1",  "2",  "1",  "1",  "1",  "1",  "",  "",
]

[[layout]]
name = "Minor Thirds 1"
scale_name = "Minor Thirds 1"

[[scale]]
name = "Harmonic Sequence"
type = "Generic"
base_pitch = "220*^1|4"
pitches = [
"57/8", "58/8", "59/8", "60/8", "61/8", "62/8", "63/8", "64/8",
"49/8", "50/8", "51/8", "52/8", "53/8", "54/8", "55/8", "56/8",
"41/8", "42/8", "43/8", "44/8", "45/8", "46/8", "47/8", "48/8",
"33/8", "34/8", "35/8", "36/8", "37/8", "38/8", "39/8", "40/8",
"25/8", "26/8", "27/8", "28/8", "29/8", "30/8", "31/8", "32/8",
"17/8", "18/8", "19/8", "20/8", "21/8", "22/8", "23/8", "24/8",
"9/8", "10/8", "11/8", "12/8", "13/8", "14/8", "15/8", "16/8",
"1/8", "2/8", "3/8", "4/8", "5/8", "6/8", "7/8", "8/8",
]
note_names = [
"57", "58", "59", "60", "61", "62", "63", "64",
"49", "50", "51", "52", "53", "54", "55", "56",
"41", "42", "43", "44", "45", "46", "47", "48",
"33", "34", "35", "36", "37", "38", "39", "40",
"25", "26", "27", "28", "29", "30", "31", "32",
"17", "18", "19", "20", "21", "22", "23", "24",
"9", "10", "11", "12", "13", "14", "15", "16",
"1", "2", "3", "4", "5", "6", "7", "8",
]

[[layout]]
name = "Harmonic Sequence"
scale_name = "Harmonic Sequence"
