[[scale]]
name = "EDO-12"
type = "EqualDivision"
divisions = [12, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C♯", "D", "E♭", "E", "F", "F♯", "G", "G♯", "A", "B♭", "B"]

[[layout]]
name = "EDO-12-2x1"
base = [2, 3]
scale_name = "EDO-12"
steps = [2, 1]

[[scale]]
name = "EDO-19"
type = "EqualDivision"
divisions = [19, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C♯", "D♭", "D", "D♯", "E♭", "E", "E♯", "F", "F♯", "G♭",
              "G", "G♯", "A♭", "A", "A♯", "B♭", "B", "B♯"]

[[layout]]
name = "EDO-19-2x1"
base = [2, 3]
scale_name = "EDO-19"
steps = [3, 2]

[[scale]]
name = "EDO-31"
type = "EqualDivision"
# reference_freq is the pitch of the base of the scale and assigned MIDI note 60
# in adjusted MIDI mode. It would would typically be middle C for something used
# as a diatonic scale.
divisions = [31, 2, 1]   # 31 divisions of the octave: [a, b, c] = ((b^c)^*(1/a))
base_pitch = "220*^3|12" # middle C for A-440 12-TET scale
note_names = [
  "C",
  "C↑", "C♯", "D♭", "D↓", "D",
  "D↑", "D♯", "E♭", "E↓", "E",
  "E↑", "F↓", "F",
  "F↑", "F♯", "G♭", "G↓", "G",
  "G↑", "G♯", "A♭", "A↓", "A",
  "A↑", "A♯", "B♭", "B↓", "B",
  "B↑", "C↓",
]

[[layout]]
name = "EDO-31-5x3"
base = [3, 3]
scale_name = "EDO-31"
steps = [5, 3]

[[scale]]
name = "EDO-17"
type = "EqualDivision"
divisions = [17, 2, 1]
base_pitch = "220*^3|12"
note_names = ["C", "C#-", "C#+", "D+", "E%-", "E-", "E+", "F", "F#-",
              "F#+", "G", "A%-", "A%+", "A+", "B%-", "B-", "B+", "C"]

[[layout]]
name = "EDO-17-2x1"
base = [2, 3]
scale_name = "EDO-17"
steps = [3, 2]

[[scale]]
name = "JI-11"
type = "Generic"
base_pitch = "55*^3|12"
pitches = [
  "[61]*2", "[62]*2", "[63]*2", "[64]*2", "[65]*2", "[66]*2", "[67]*2", "[68]*2",
  "[51]*2", "[52]*2", "[53]*2", "[54]*2", "[55]*2", "[56]*2", "[57]*2", "[58]*2",
  "[41]*2", "[42]*2", "[43]*2", "[44]*2", "[45]*2", "[46]*2", "[47]*2", "[48]*2",
  "[31]*2", "[32]*2", "[33]*2", "[34]*2", "[35]*2", "[36]*2", "[37]*2", "[38]*2",
  "[21]*2", "[22]*2", "[23]*2", "[24]*2", "[25]*2", "[26]*2", "[27]*2", "[28]*2",
  "[11]*2", "[12]*2", "[13]*2", "[14]*2", "[15]*2", "[16]*2", "[17]*2", "[18]*2",
  "17/16",  "16/15",   "6/5",   "11/8",   "17/12",  "8/5",     "7/4",   "16/9",
   "1",      "9/8",    "5/4",    "4/3",    "3/2",   "5/3",    "15/8",    "2",
]
note_names = [
 "C♯'", "D♭'", "E♭'", "H11'", "F♯'", "A♭'", "H7'", "B♭'",
 "C'",  "D'",  "E'",  "F'",   "G'",  "A'",  "B'",  "C'",
 "C♯", "D♭", "E♭", "H11", "F♯", "A♭", "H7", "B♭",
 "C",  "D",  "E",  "F",   "G",  "A",  "B",  "C",
 "C♯,", "D♭,", "E♭,", "H11,", "F♯,", "A♭,", "H7,", "B♭,",
 "C,",  "D,",  "E,",  "F,",   "G,",  "A,",  "B,",  "C,",
 "C♯,,", "D♭,,", "E♭,,", "H11,,", "F♯,,", "A♭,,", "H7,,", "B♭,,",
 "C,,",  "D,,",  "E,,",  "F,,",   "G,,",  "A,,",  "B,,",  "C,,",
]

[[layout]]
name = "Just Intonation (11)"
scale_name = "JI-11"

[[scale]]
# From Fabio Costa minor third etude: https://www.youtube.com/watch?v=U7l7s1Vr6lQ
name = "Minor Thirds 1"
type = "Generic"
base_pitch = "990.8"
# In spite of frequencies listed in the video, the lower note of the
# third always appears to have the same frequency.
pitches = [
  "15/13", "37/32", "22/19", "29/25", "36/31", "50/43", "7/6", "55/47",
   "1",     "1",     "1",     "1",     "1",     "1"   , "1",    "1",
  "11/13", "27/32", "16/19", "21/25", "26/31", "36/43", "5/6", "39/47",
  "9/13",  "22/32", "13/19", "17/25", "21/31", "29/43", "4/6", "31/47",
  "7/13",  "17/32", "10/19", "13/25", "16/31", "22/43", "3/6", "23/47",
  "5/13",  "12/32",  "7/19",  "9/25", "11/31", "15/43", "2/6", "15/47",
  "3/13" ,  "7/32",  "4/19",  "5/25",  "6/31", "08/43", "1/6",  "7/47",
  "1/13" ,  "2/32",  "1/19",  "1/25",  "1/31", "01/43",  "",     "",
]
note_names = [
   "15", "37", "22", "29", "36", "50", "7", "55",
   "13", "32", "19", "25", "31", "43", "6", "47",
   "11", "27", "16", "21", "26", "36", "5", "39",
    "9", "22", "13", "17", "21", "29", "4", "31",
    "7", "17", "10", "13", "16", "22", "3", "23",
    "5", "12",  "7",  "9", "11", "15", "2", "15",
    "3",  "7",  "4",  "5",  "6",  "8", "1",  "7",
    "1",  "2",  "1",  "1",  "1",  "1",  "",  "",
]

[[layout]]
name = "Minor Thirds 1"
scale_name = "Minor Thirds 1"
