[[scale]]
name = "Elegy-1"
type = "Generic"
base_pitch = "220*^3|12"
pitches = [
  "", "", "", "", "", "", "", "",
  "^2|17", "^5|17", "",      "^9|17", "^12|17", "^15|17", "", "",
  "^1|17", "^4|17", "",      "^8|17", "^11|17", "^14|17", "", "",
  "1",     "^3|17", "^6|17", "^7|17", "^10|17", "^13|17", "^16|17", "",
  "[71]*1/2", "[72]*1/2", "", "[74]*1/2", "[75]*1/2", "[76]*1/2", "", "",
  "[61]*1/2", "[62]*1/2", "", "[64]*1/2", "[65]*1/2", "[66]*1/2", "", "",
  "[51]*1/2", "[52]*1/2", "[53]*1/2", "[54]*1/2", "[55]*1/2", "[56]*1/2", "[57]*1/2", "1/4*^7|17",
  "", "1/4*^-4|17", "1/4*^-2|17", "1/4", "1/4*^2|17", "1/4*^3|17", "1/4*^4|17", "1/4*^5|17",
]
note_names = [
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
]

[[layout]]
name = "Elegy-1"
scale_name = "Elegy-1"

[[scale]]
name = "Elegy-2"
type = "Generic"
base_pitch = "220*^3|12"
pitches = [
  "^3|17", "^7|17", "^11|17", "^15|17", "",  "", "", "",
  "^2|17", "^6|17", "^10|17", "^14|17", "",  "", "", "",
  "^1|17", "^5|17", "^9|17", "^13|17", "",   "", "", "",
  "1", "^4|17", "^8|17", "^12|17", "^16|17", "", "", "",
  "^-14|17", "^-10|17", "^-6|17", "^-2|17", "",  "", "", "",
  "^-15|17", "^-11|17", "^-7|17", "^-3|17", "",  "1/4",        "1/4*^4|17", "1/4*^7|17",
  "^-16|17", "^-12|17", "^-8|17", "^-4|17", "",   "1/4*^-2|17", "1/4*^3|17", "",
  "1/2", "^-13|17", "^-9|17", "^-5|17", "^-1|17", "1/4*^-4|17", "1/4*^2|17", "1/4*^5|17",
]
note_names = [
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "",
]

[[layout]]
name = "Elegy-2"
scale_name = "Elegy-2"
