# The URL the site will be built for
base_url = "https://syntoniq.cc/manual/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "book"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

extra_syntaxes_and_themes = ["syntaxes"]
# Note: Zola comes with many built-in themes.
#highlight_theme = "base16-ocean-dark"
#highlight_theme = "monokai"
highlight_theme = "boron"

[extra]
# Put all your custom variables here
